version: '3.1'

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=woungsub123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=woungsub123
      - MYSQL_DATABASE=livrodb
  app:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
      - ./:/src/node_modules

dependencies:
  restart: always
  ports:
    - '3000:3000'
  links:
    - mysql
  depends_on:
    - mysql
