version: '3.1'

networks:
  app-tier:
    driver: bridge
services:
  docker-livro:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
      - ./:/src/node_modules

dependencies:
  restart: always
  ports:
    - '3000:3000'
